name: "ESLint"
on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: npm

      - name: Install Node modules
        run: npm install --ignore-scripts

      - name: Lint
        run: |
          npm run lint
